language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
before_install:
  # Setup Node.js version-specific dependencies
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm rm --save-dev istanbul"
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
script:
  # Run test script, depending on istanbul install
  - "test -n $(npm -ps ls istanbul) || npm test"
  - "test -z $(npm -ps ls istanbul) || npm run-script test-travis"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
